"""agents can be assigned multiple elective positions

Revision ID: 2cfae5ed4e54
Revises: bed158bf3def
Create Date: 2026-08-24 12:49:07.740145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cfae5ed4e54'
down_revision = 'bed158bf3def'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_position',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('position_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['elective_position.id'], ),
    sa.PrimaryKeyConstraint('agent_id', 'position_id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_agent_position_id'), type_='foreignkey')
        batch_op.drop_column('position_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position_id', sa.UUID(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_agent_position_id'), 'elective_position', ['position_id'], ['id'])

    op.drop_table('agent_position')
    # ### end Alembic commands ###
