"""initial schema

Revision ID: 9c48c38371ce
Revises: 
Create Date: 2026-08-23 16:04:33.421886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c48c38371ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('party', sa.Text(), nullable=True),
    sa.Column('ballot_position', sa.SmallInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ballot_position')
    )
    op.create_table('constituency',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('otp_code',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ward',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('constituency_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['constituency_id'], ['constituency.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('constituency_id', 'name')
    )
    op.create_table('polling_station',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ward_id', sa.UUID(), nullable=False),
    sa.Column('iebc_code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('registered_voters', sa.Integer(), nullable=True),
    sa.Column('stream_count', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['ward_id'], ['ward.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iebc_code')
    )
    op.create_table('agent',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('phone_number', sa.Text(), nullable=False),
    sa.Column('phone_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('assigned_station_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['assigned_station_id'], ['polling_station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('form_submission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('form_type', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('image_sha256', sa.Text(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_votes_cast', sa.Integer(), nullable=True),
    sa.Column('rejected_ballots', sa.Integer(), nullable=True),
    sa.Column('ocr_confidence_avg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('duplicate_of', sa.UUID(), nullable=True),
    sa.Column('warnings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['duplicate_of'], ['form_submission.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['polling_station.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'form_type', 'image_sha256')
    )
    op.create_table('verification_log',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('reviewer_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewer_id'], ['agent.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submission.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vote_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('submission_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('votes_detected', sa.Integer(), nullable=False),
    sa.Column('votes_corrected', sa.Integer(), nullable=True),
    sa.Column('field_confidence', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('manually_overridden', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidate.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['form_submission.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id', 'candidate_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote_record')
    op.drop_table('verification_log')
    op.drop_table('form_submission')
    op.drop_table('agent')
    op.drop_table('polling_station')
    op.drop_table('ward')
    op.drop_table('otp_code')
    op.drop_table('constituency')
    op.drop_table('candidate')
    # ### end Alembic commands ###
